### PR TITLE
Bring back Kitty underlines!

### LINKED ISSUE #802: `Text` composable broken on native
Started with #765 (bisected to 8957294eff99f6ca3b744b12e146b8131ac1b3ad). Not sure why, but probably Compose compiler bug.

### PR DESCRIPTION
**Pull request by JakeWharton**
The difference in `UnderlineStyle` as opposed to `Color` and `TextStyle` was that it had a `private` constructor. Changing that to `internal` like the others avoids the compiler bug.

Closes #802 

---

- [x] `CHANGELOG.md`'s "Unreleased" section has been updated, if applicable.

### CODE REVIEW

File: mosaic-runtime/src/commonMain/kotlin/com/jakewharton/mosaic/ui/UnderlineStyle.kt [hunk 1]
```diff
@@ -8,7 +8,7 @@ import kotlin.jvm.JvmInline
 
 @Immutable
 @JvmInline
-public value class UnderlineStyle private constructor(
+public value class UnderlineStyle internal constructor(
```
Comment (mattprecious) [inline mosaic-runtime/src/commonMain/kotlin/com/jakewharton/mosaic/ui/UnderlineStyle.kt:12]: Worth commenting that this cannot be private due to the bug?

Comment (JakeWharton) [reply mosaic-runtime/src/commonMain/kotlin/com/jakewharton/mosaic/ui/UnderlineStyle.kt:12]: Sure. I did also change the build configuration so it will fail if you try.
